services:
  - docker

dist: trusty
language: python

python:
  - "3.6"

install:
  - pip install requests

addons:
  hosts:
    - webfacerecognition.local
  
env:
  COMPOSE_VERSION: 1.23.1
  BACKUP_URL: https://github.com/pedrohenriquebr/web-face-recognition/raw/backups/backup-2019-07-05.zip

before_script:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - wget -c "$BACKUP_URL" -O backup.zip
  - echo "A" | unzip -x backup.zip
  - bash standard.sh
  - make build
  - make run-dev
  - make encoding
  - make train
  - make clean
  - make build
  - make run
  - docker-compose logs
  - sleep 15
  - for i in testset/*.jpeg; do python3 recog.py $i; sleep 30; done
  - docker-compose logs
