services:
  - docker

dist: trusty

env:
  COMPOSE_VERSION: 1.23.1

before_script:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make build
  - make run-dev
  - docker-compose logs
