version: '3'
services:
  web:
    build: .
    image: web_face_recognition:latest
    ports:
      - ${PORT}:5000
    env_file:
      - ./.env
    volumes:
      - ./src:/root/face_recognition:ro
      - ./dataset:/dataset:ro
      - ./modelset:/modelset:rw
    labels:
      - 'app.environment=${ENV_APP}'
      

