version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
  web:
    build: .
    image: web_face_recognition:latest
    env_file:
      - ./.env
    volumes:
      - ./src:/root/face_recognition:ro
      - ./dataset:/dataset:ro
      - ./modelset:/modelset:rw
    labels:
      - 'app.environment=${ENV_APP}'
      

