version: '3'
services:
  web:
    build: .
    image: pedrobraga/web_face_recognition:latest
    env_file:
      - ./.env
    volumes:
      - ./src:/root/face_recognition:ro
      - ./dataset:/dataset:rw
      - ./modelset:/modelset:rw
    labels:
      - 'app.environment=${ENV_APP}'
    ports: 
      - "5000:5000"