version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "${PORT:-5000}:80"
  web:
    image: pedrobraga/web_face_recognition:latest
    env_file:
      - ./.production.env
    volumes:
      - ./modelset:/modelset/:ro
    labels:
      - 'app.environment=${ENV_APP}'