version: '3'
services:
  web:
    image: ${USERNAME}/web_face_recognition:${TAG}
    ports:
      - 5000-5005:5000
    env_file:
      - ./.production.env
    labels:
      - 'app.environment=${ENV_APP}'